'sample diagram

@startuml
if (temperature > 30 && humidity >= 70) then (yes)
' temperature > 30 && humidity >= 60
    :air conditioner is Dry mode;
else 
    :air conditioner is cooling mode;
@enduml
